import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

// Components
import { Login } from "../components/Login/Login";
// Styles
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Pet app - login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Login />
    </div>
  );
};

export default Home;
